### ISSUE TITLE
A PHP Error was encountered - CSZ-CMS Version 1.2.2

### ISSUE THREAD

**Issue by GaneshKandu** [cskaza/cszcms#18]
Hi,

Getting following error  in CSZ-CMS Version 1.2.2
All time when i login to admin panel

```
A PHP Error was encountered

Severity: Warning

Message: Cannot modify header information - headers already sent by (output started at cszcms/models/Csz_admin_model.php:2885)

Filename: helpers/url_helper.php

Line Number: 561

Backtrace:

File: cszcms/controllers/admin/Admin.php
Line: 262
Function: redirect

File: index.php
Line: 345
Function: require_once


Powered by CSZ CMS | Open Source Content Management with responsive 
```
cszcms/models/Csz_admin_model.php:2885 Echoing text before header function that causing error 

```php
    public function showLoadingImg() {
        echo '<center><div style="position:fixed;top:50%;left:50%;transform:translate(-50%,-50%)"><img src="'.base_url('', '', TRUE).'assets/images/loading.gif" class="img-responsive"/><br>Loading...</div></center>';
    }
```
system\helpers\url_helper.php:561 using ```header```
```php
		switch ($method)
		{
			case 'refresh':
				header('Refresh:0;url='.$uri);
				break;
			default:
				header('Location: '.$uri, TRUE, $code);
				break;
		}
```

**Comment by cskaza** [comment]
Thanks for your issue.

I think you test on localhost with XAMPP.
Please config the php.ini
On error_reporting=E_ALL
change to error_reporting=E_ALL & ~E_NOTICE & ~E_STRICT

It will resolve this problem.
But in the PHP coding. I try to review and fix on next version again.
On cszcms/models/Csz_admin_model.php:2885 i will put like this
 ```
public function showLoadingImg() {
        echo '<center><div style="position:fixed;top:50%;left:50%;transform:translate(-50%,-50%)"><img src="'.base_url('', '', TRUE).'assets/images/loading.gif" class="img-responsive"/><br>Loading...</div></center>';
        exit();
    }
```

Normally on production hosting. This PHP setting is "E_ALL & ~E_NOTICE & ~E_STRICT"

**Comment by cskaza** [comment]
Now, This issue been resolved.
[https://github.com/cskaza/cszcms/commit/9db529ea598a39622d3d6d97a596894805b46f9f](url)

You can download the file from
https://github.com/cskaza/cszcms/releases/download/1.2.2/upgrade-1.2.2-fixbug.zip

And extract this file and replace on CSZCMS old file.
