### ISSUE TITLE
There is an arbitrary file upload vulnerability

### ISSUE THREAD

**Issue by Bla1n** [cskaza/cszcms#20]
There are any files uploaded in the background of your website, you can upload PHP files, so that if the administrator password is leaked, the file uploaded through here can be directly getshell, take over the web
example:
![图片](https://user-images.githubusercontent.com/44456023/61187664-f06d7d00-a6a6-11e9-8bed-4b1689c31668.png)
![图片](https://user-images.githubusercontent.com/44456023/61187668-00855c80-a6a7-11e9-8192-50c824424e28.png)
I think you should limit the type of file you upload

**Comment by cskaza** [comment]
administrator password is leaked. It's user error.

And on this section. I want to use like a file manager.
I can edit/ upload with replace the php file without FTP.

**Comment by cskaza** [comment]
Fixed already on 1.2.4
Thanks.
