### ISSUE TITLE
Arbitrary file upload vulnerability in CSZCMS-1.2.4

### ISSUE THREAD

**Issue by edwatering** [cskaza/cszcms#21]
Hi, @cskaza and I found an arbitrary file upload vulnerability in admin/filemanager. The vulnerable code is on filemanager.php file line 711 and function 'cmsConfigAdmin'.The config of 'CSZCMS System Config' allow upload Arbitrary file. I can upload a webshell to take over the web server.
![20191113-164358](https://user-images.githubusercontent.com/3412787/68747178-fa8f9000-0634-11ea-9b97-24d68caa1afd.jpg)

The file after uploading, available at this link : http://localhost/cszcms/webshell.php

![CAC3E7D2-EF1B-45a5-99C4-BA8EE1B33AF5](https://user-images.githubusercontent.com/3412787/68747594-d2546100-0635-11ea-9f74-4f659b884695.png)

**Comment by edwatering** [comment]
I know you want use it like a file manager. But the edit/upload is very dangerous section，you must code cautious.
The security is not a barrier of the section. It's a features of the cms.

**Comment by cskaza** [comment]
Thanks for your suggest. That is third-party plugin.
I think I can disable the upload function on this section.

**Comment by cskaza** [comment]
This bug has been to resolved.
https://gitlab.com/cszcms/cszcms/commit/b5d9868a93706abd74d97bcaf50745efb0e1cc93

Thanks.
