### ISSUE TITLE
Bug Report: SQL injection vulnerability

### ISSUE THREAD

**Issue by cuhanboy** [cskaza/cszcms#26]
Hi, @cskaza I found a high-risk time-based blind SQL injection vulnerability in the member function module.
（http://website/member/edit）
![image](https://user-images.githubusercontent.com/45351599/103391758-f8003a80-4b55-11eb-9d30-b797e309761d.png)
the vulnerable code is on cszcms/models/csz_model.php 
![image](https://user-images.githubusercontent.com/45351599/103391806-1fef9e00-4b56-11eb-8d48-5d14498f2382.png)
The vulnerability parameter is  pm_sendmail.This parameter is passed to the database query without any filtering, resulting in a vulnerability.
![image](https://user-images.githubusercontent.com/45351599/103391846-4a415b80-4b56-11eb-99a2-f51752f1bd10.png)
All the data in the database can be obtained by using sqlmap.
![image](https://user-images.githubusercontent.com/45351599/103392143-6db8d600-4b57-11eb-9766-dfbccfa58657.png)

**Comment by cskaza** [comment]
Resolved done on next version.
