### ISSUE TITLE
Bug Report:Arbitrary delete file vulnerability

### ISSUE THREAD

**Issue by cuhanboy** [cskaza/cszcms#27]
Hi, @cskaza I found a file deletion vulnerability  in the member function module.
(http://website/member/edit)
The "del_file" parameter is directly sent to the unlink function for file deletion without filtering.This can cause files in the system to be deleted arbitrarily.
The vulnerable code is on cszcms/models/csz_model.php. 
![image](https://user-images.githubusercontent.com/45351599/103400499-3e6a8f00-4b80-11eb-9382-bdecaa9ff436.png)
exp:
First, register a member and upload any picture in the personal information.
![image](https://user-images.githubusercontent.com/45351599/103400084-ccde1100-4b7e-11eb-832e-f87490074404.png)
After the upload is successful, edit the personal information again and check delete file.
![image](https://user-images.githubusercontent.com/45351599/103400532-6eb22d80-4b80-11eb-9ac8-9d89bdf2b68c.png)
If you change the "del_file" parameter to "../../config.inc.php", you can delete the website configuration file, resulting in the website not being used normally.
![image](https://user-images.githubusercontent.com/45351599/103400556-84275780-4b80-11eb-991d-8b638694ee26.png)
Because the configuration file has been deleted, the system jumps to the installation page.
![image](https://user-images.githubusercontent.com/45351599/103400567-90abb000-4b80-11eb-9362-059110b1bd7f.png)

**Comment by cskaza** [comment]
Resolved done on next version.
