### ISSUE TITLE
Cszcms 

### ISSUE THREAD

**Issue by Poncho09** [cskaza/cszcms#4]
According to the conversation, established with the main developer of cszcms @cskaza, the cszcms project happens to be hosted and maintained by the Astian Foundation http://astian.org. 

Where the founder and main developer will continue as leader of the development and being member of the foundation. But they will change some things like for example the licensing of the cszcms files while the codeigniter files will continue under MIT, functionalities, characteristics among other things.

Soon the cszcms project will be within the domains of the foundation.

Great changes are coming and we hope that next to the foundation this project will continue to grow and reach new horizons.

Thanks

**Comment by cskaza** [comment]
Your Welcome, Astian Foundation.
:)

**Comment by Poncho09** [comment]
Thanks @cskaza
