### ISSUE TITLE
Bug on Install Now

### ISSUE THREAD

**Issue by AlexKyocom** [cskaza/cszcms#5]
When it comes to installing cszcms in a test environment when you press the install button it goes blank.

![screenshot_20161129_115741](https://cloud.githubusercontent.com/assets/20441703/20720263/80e8b796-b62c-11e6-935e-6d41815f04fe.png)

Thanks

**Comment by cskaza** [comment]
I see in http://www.astian.org/prueba/ the website has been installed. But when I fix all bug in 1.1.4 beta. I can send the new install file for you. I want to know why when you press the install and show blank page.
Thanks. :)
