### ISSUE TITLE
Integration GroceryCRUD

### ISSUE THREAD

**Issue by AlexKyocom** [cskaza/cszcms#6]
Grocery CRUD is an open source library that makes a developer's life easier. Few simple lines of code and you can create a full stable CRUD with nice views. A completely automatic system that even a newbie in PHP can work with.

http://www.grocerycrud.com/ this is one library what facilitate the creation of CRUD.

**simple example** 
```php


function offices()
{
$output = $this->grocery_crud->render();
 
$this->_example_output($output);
}
```
![screenshot_20161129_121544](https://cloud.githubusercontent.com/assets/20441703/20720573/aa232d48-b62d-11e6-9b7c-2178f9754ebb.png)

**Full Example**

```php
function my_boss_is_in_a_hurry()
{
$crud = new grocery_CRUD();
$crud->set_table('customers');
$crud->columns('customerName','phone','addressLine1','creditLimit');
 
$output = $crud->render();
 
$this->_example_output($output);
}
```
![screenshot_20161129_121654](https://cloud.githubusercontent.com/assets/20441703/20720581/baf49896-b62d-11e6-933d-cb741bb00386.png)

**Comment by cskaza** [comment]
I think it's interesting! But not in version 1.1.4 because I want to fix about security and other bug.
Thanks :)
