### ISSUE TITLE
error script sql table user_admin

### ISSUE THREAD

**Issue by AlexKyocom** [cskaza/cszcms#8]
![screenshot_20161129_132327](https://cloud.githubusercontent.com/assets/20441703/20723064/07ae0f42-b637-11e6-8ad8-e6b8e031821e.png)

field 
- `first_name` varchar(255) NOT NULL,
-   `last_name` varchar(255) NOT NULL,
-   `birthday` date NOT NULL,
-   `gender` varchar(10) NOT NULL,
-   `address` text NOT NULL,
-   `phone` varchar(100) NOT NULL,
- `picture` varchar(255) NOT NULL,

```sql
INSERT INTO `user_admin` (`user_admin_id`, `name`, `email`, `password`, `user_type`, `active`, `md5_hash`, `md5_lasttime`, `timestamp_create`, `timestamp_update`) VALUES 
(1, 'Admin User', 'demo@cszcms.com', '10470c3b4b1fed12c3baac014be15fac67c6e815', 'admin', 1, '11fbf7460f6c7e9d03602195b88f54b1', NOW(), NOW(), NOW());

```

**Comment by cskaza** [comment]
Can you explain me about where is error script for this sql?

**Comment by Poncho09** [comment]
The error is in the INSERT since you are requesting or requesting fields to fill that INSERT are not

**Comment by cskaza** [comment]
You think we want insert with all field?

**Comment by Poncho09** [comment]
Of course being NOT NULL the fields you are indicating to the system that those fields can not be empty or unknown, that is must be filled

**Comment by cskaza** [comment]
I remove NOT NULL from sql installer now.
