### ISSUE TITLE
Session error

### ISSUE THREAD

**Issue by Poncho09** [cskaza/cszcms#9]
The problem is that when creating or editing a page but if it exceeds a time of 10 or 15 minutes and after this time is pressed the Save button, it throws an error.

I think the connection or session is lost or the cookie closes the connection.

This error also affects the login when you are logged in.

**Comment by cskaza** [comment]
Hi, Poncho09

Please use 1.1.4 beta for test it again. I want to know about this problem has been fixed.
https://www.cszcms.com/downloads/install/cszcms-1.1.4-beta.zip

**Comment by Poncho09** [comment]
thanks my friend
